name: netguru_values
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  get: ^3.17.1
  equatable: ^1.2.5
  dartz: ^0.9.2
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  responsive_framework: ^0.0.11
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^0.8.2
  build_runner: ^1.10.6

flutter:
  uses-material-design: true